# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-12 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartNo_PartName', models.CharField(max_length=100)),
                ('SupplierCode', models.CharField(max_length=100)),
                ('SupplierName', models.CharField(max_length=30)),
                ('ControlPlanVersion', models.IntegerField()),
                ('PDIPlanVersion', models.IntegerField()),
                ('Uploaded_on', models.CharField(max_length=30)),
                ('Download_Upload', models.CharField(max_length=10)),
            ],
        ),
    ]
