# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-12 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XlGetter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlplan',
            name='PDIPlanVersion',
            field=models.CharField(max_length=30),
        ),
    ]
